name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Runs every 6 hours
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: devvinelima
          svg_out_path: dist/snake.svg
          dark_mode: true

      - name: Push snake.svg to output branch
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg

      - name: Checkout output branch
        uses: actions/checkout@v3
        with:
          ref: output
          path: output_dir

      - name: Copy snake.svg to output branch
        run: |
          cp dist/snake.svg output_dir/snake.svg

      - name: Commit and push to output branch
        working-directory: ./output_dir
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add snake.svg
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
